[[main]]
none = "none"

[[main]]
name = "ÍNICIO"
pageRef = "/"
identifier = "r1o0NT52zu"
weight = 10

[[main]]
name = "POSTS"
pageRef = "/posts"
identifier = "ELpNGOazZR"
weight = 20

[[main]]
name = "SLACKBUILDS"
url = "https://github.com/eurodrigolira/slackbuilds"
identifier = "PsCQ91j983"
weight = 30

[[main]]
name = "ISOS"
url = "https://rodrigolira.eti.br"
identifier = "mOx4trG62W"
weight = 40

[[main]]
name = "CATEGORIAS"
pageRef = "/categories"
identifier = "XLK78KBSzH"
weight = 50

[[footer]]
  name = "TAGS"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "CATEGORIAS"
  pageRef = "categories"
  weight = 20

